# Mandatory settings

blog_theme: light # Or use dark
name: Pedro Madruga
paginate: 10
url: https://pedromadruga.com

# Optional settings
about_enabled: false # Change to true if you wish to show an icon in the navigation that redirects to the about page
baseurl: ""
discus_identifier: # Add your Disqus identifier
# ga_analytics: UA-38416409-1
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: false # Change to false if not
scrollappear_enabled: false # Change to false to disable
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: pmadruga
  linkedin: pedromadruga
  twitter: isaacsthirdlaw
  bitcoin: # Add your Bitcoin link or address
  ethereum: # Add your Ethereum link or address
  gitlab: # Add your GitLab handle
  youtube: # Add your Youtube handle
  twitch: # Add your Twitch handle
  discord: # Add you Discord server invitation ID
  tumblr: # Add your Tumblr handle
  bitbucket: # Add your Bitbucket handle
  docker: # Add your Docker Hub handle
  instagram: #pedroforaday
  keybase: # Add your Keybase handle
  medium: "@pmadruga"
  spotify: # Add your Spotify handle
  stackoverflow: 12418383
  steam: # Add your Steam handle

# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: {} }
    img: { optim: {} }
    jekyll-minifier:
      preserve_php: true # Default: false
      remove_spaces_inside_tags: true # Default: true
      remove_multi_spaces: true # Default: true
      remove_comments: true # Default: true
      remove_intertag_spaces: true # Default: false
      remove_quotes: false # Default: false
      compress_css: true # Default: true
      compress_javascript: true # Default: true
      simple_doctype: false # Default: false
      remove_script_attributes: false # Default: false
      remove_style_attributes: false # Default: false
      remove_link_attributes: false # Default: false
      remove_form_attributes: false # Default: false
      remove_input_attributes: false # Default: false
      remove_javascript_protocol: false # Default: false
      remove_http_protocol: false # Default: false
      remove_https_protocol: false # Default: false
      preserve_line_breaks: false # Default: false
      simple_boolean_attributes: false # Default: false
      compress_js_templates: true # Default: false
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
    - _assets/documents
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  - scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
  - docs
  - node_modules
destination: docs
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-email-protect
paginate_path: /blog/page/:num/
image_optim:
  archive_dir: "_assets/images/originals"
  cache_file: "tmp/_image_optime_cache.yml"
  image_glob: "build/assets/images/**/*.{gif,png,jpg,jpeg}"
#permalink: posts/:slug
